#!/usr/bin/env bash

set -e

{
  cargo build --release

  (
    cd crates/python || exit 1
    maturin build --release
    cp ../../target/wheels/quantum_animal_shogi-0.1.0-cp313-cp313-manylinux_2_34_x86_64.whl ../../../dist
  )

  (
    cd crates/wasm || exit 1
    wasm-pack build --release
  )
} || {
  echo "Feiled..." >&2
}
